### ISSUE TITLE
Multiple credentials and access key regarding the changing access key of a user

### ISSUE THREAD

**Issue by mrnim94** [mrnim94/zeus#42]
Each schedule only changes the access key or a credential. It's not reasonable in the actual case.

Each schedule will change multiple access keys and credentials.
```yaml
schedules:
  - name: change-credetial-aws
    cron: "*/1 * * * *"
    usernameOnAws: nimtechnology
    namespaceOnK8s: default
    locations:
      - secretName: credentials-aws
        style: CredentialOnK8s
        credentialOnK8s: credentials
        profile: dev
      - secretName: secret-aws
        style: AccessKeyOnK8s
        accessKeyOnK8s: accesskey
        secretKeyOnK8s: secretkey
    restartWorkloads:
      - kind: deployment
        name: "argo-workflow-argo-workflows-server"
```
